# almalinux is exactly same as Redhat image, but completely free
FROM almalinux:9
LABEL COURSE="Docker" \
      TRAINER="Naveen" \
      version="1.0" \
      description="This is a sample Dockerfile for creating a custom image based on almalinux" \
      AUTHOR="devopswitnaveen"