ARG version
FROM almalinux:${version:-8}
ARG COURSE="Docker" \
    TRAINER="Naveen" \
    version="8" \
    AUTHOR="devopswitnaveen"
RUN echo "Trainer is: ${TRAINER}, version is: ${version}"
CMD ["sleep", "200"]